name: Node.js CI

on:
  pull_request:
    branches: [ Dev, Stage ]

jobs:
  build:
    # Runs on the latest Ubuntu virtual machine
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up the Node.js environment
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Specify the desired Node.js version
        # Caches npm dependencies for faster subsequent runs
        cache: 'npm'
        cache-dependency-path: App/AppointMentService/package-lock.json

    # Step 3: Install dependencies
    - name: Install dependencies for appointment service
      working-directory: App/AppointMentService
      # Using 'npm ci' is recommended for CI/CD environments as it's faster and more reliable
      run: npm install

    - name: Install dependencies for PatientMonitoring service
      working-directory: App/PatientService
      # Using 'npm ci' is recommended for CI/CD environments as it's faster and more reliable
      run: npm install

    # Step 4: Build the application if a build script exists
    - name: Build application AppointMentService
      working-directory: App/AppointMentService
      run: npm run build 

    - name: Build application PatientService
      working-directory: App/PatientService
      run: npm run build 
