name: Build Docker Image

on:
  push:
    branches: ["main", "Dev"]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for Appointment
        run: docker build -f Dockerfile-appointment -t appointment-service .

      - name: Build Docker image for Patient
        run: docker build -f Dockerfile-patient -t patient-service .
