name: AWS S3 Bucket

# Trigger the workflow every push to branch "main"
on:
  push:
    branches: [ "main" ]

# Necessary permissions for workflow
permissions:
  id-token: write
  contents: read

jobs:
  S3BucketIntegration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install awscli
      - uses: unfor19/install-aws-cli-action@v1
      
      # Assume the OIDC Role to get temporary credentials 
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::768132174891:role/poc-2-tp-role
  
      # List all buckets
      - name: List S3 Bucket
        run: |
          echo "==> Listing all S3 buckets"
          aws s3 ls # This is a basic workflow to help you get started with Actions
